## Matrix Norms

In [11033469]:
linalg.norm(myArr)

5.477225575051661

In [13196044]:
linalg.norm(myArr,'fro')

5.477225575051661

In [10021929]:
linalg.norm(myArr,1)

6.0

In [11911211]:
linalg.norm(myArr,-1)

4.0

In [12605393]:
linalg.norm(myArr,np.inf)

7.0

In [9632077]:
import numpy as np
from scipy import linalg
myArr = np.array([[1,2],[3,4]])

<module 'numpy' from '/home/pc/miniconda3/lib/python3.6/site-packages/numpy/__init__.py'>

<module 'scipy.linalg' from '/home/pc/miniconda3/lib/python3.6/site-packages/scipy/linalg/__init__.py'>

array([[1, 2],
       [3, 4]])

## SVD in Dataflow

In [12162461]:
myArr.shape

(2, 2)

In [14640226]:
svdArr = linalg.svd(myArr)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [874562]:
linalg.diagsvd(svdArr[1],Out['b9959d'][0],Out['b9959d'][1])

array([[5.4649857 , 0.        ],
       [0.        , 0.36596619]])

In [8848078]:
svdArr[0].dot(Out['0d5842'].dot(svdArr[2]))

array([[1., 2.],
       [3., 4.]])

## Schur Decomposition

In [4803178]:
np.mat('[1 3 2; 1 4 5; 2 3 6]')

matrix([[1, 3, 2],
        [1, 4, 5],
        [2, 3, 6]])

In [4393724]:
linalg.schur(Out['494a6a'])

(array([[ 9.90012467,  1.78947961, -0.65498528],
        [ 0.        ,  0.54993766, -1.57754789],
        [ 0.        ,  0.51260928,  0.54993766]]),
 array([[ 0.36702395, -0.85002495, -0.37782404],
        [ 0.63681656, -0.06646488,  0.76814522],
        [ 0.67805463,  0.52253231, -0.51691576]]))

In [307116]:
linalg.schur(Out['494a6a'], 'complex')

(array([[ 9.90012467+4.44089210e-16j,  1.58629653-7.59468606e-02j,
         -0.24901757+1.02329305e+00j],
        [ 0.        +0.00000000e+00j,  0.54993766+8.99258408e-01j,
          0.51778761+9.30585972e-01j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
          0.54993766-8.99258408e-01j]]),
 array([[-0.36066189-0.06804102j,  0.7242709 -0.23617942j,
         -0.53176194-0.04662187j],
        [-0.62577787-0.11805674j,  0.08310692+0.37568066j,
          0.3351953 +0.57798448j],
        [-0.66630111-0.12570169j, -0.47009285-0.22499096j,
         -0.02697209-0.51759656j]]))

In [14934367]:
linalg.rsf2csf(Out['04afac'][0],Out['04afac'][1])

(array([[ 9.90012467+4.44089210e-16j,  1.58629653-7.59468606e-02j,
         -0.24901757+1.02329305e+00j],
        [ 0.        +0.00000000e+00j,  0.54993766+8.99258408e-01j,
          0.51778761+9.30585972e-01j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
          0.54993766-8.99258408e-01j]]),
 array([[-0.36066189-0.06804102j,  0.7242709 -0.23617942j,
         -0.53176194-0.04662187j],
        [-0.62577787-0.11805674j,  0.08310692+0.37568066j,
          0.3351953 +0.57798448j],
        [-0.66630111-0.12570169j, -0.47009285-0.22499096j,
         -0.02697209-0.51759656j]]))

In [4863022]:
T,Z,T1,Z1,T2,Z2 = map(np.mat,(Out['430afc'][0],Out['430afc'][1],Out['04afac'][0],Out['04afac'][1],Out['e3e15f'][0],Out['e3e15f'][1]))

matrix([[ 9.90012467,  1.78947961, -0.65498528],
        [ 0.        ,  0.54993766, -1.57754789],
        [ 0.        ,  0.51260928,  0.54993766]])

matrix([[ 0.36702395, -0.85002495, -0.37782404],
        [ 0.63681656, -0.06646488,  0.76814522],
        [ 0.67805463,  0.52253231, -0.51691576]])

matrix([[ 9.90012467+4.44089210e-16j,  1.58629653-7.59468606e-02j,
         -0.24901757+1.02329305e+00j],
        [ 0.        +0.00000000e+00j,  0.54993766+8.99258408e-01j,
          0.51778761+9.30585972e-01j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
          0.54993766-8.99258408e-01j]])

matrix([[-0.36066189-0.06804102j,  0.7242709 -0.23617942j,
         -0.53176194-0.04662187j],
        [-0.62577787-0.11805674j,  0.08310692+0.37568066j,
          0.3351953 +0.57798448j],
        [-0.66630111-0.12570169j, -0.47009285-0.22499096j,
         -0.02697209-0.51759656j]])

matrix([[ 9.90012467+4.44089210e-16j,  1.58629653-7.59468606e-02j,
         -0.24901757+1.02329305e+00j],
        [ 0.        +0.00000000e+00j,  0.54993766+8.99258408e-01j,
          0.51778761+9.30585972e-01j],
        [ 0.        +0.00000000e+00j,  0.        +0.00000000e+00j,
          0.54993766-8.99258408e-01j]])

matrix([[-0.36066189-0.06804102j,  0.7242709 -0.23617942j,
         -0.53176194-0.04662187j],
        [-0.62577787-0.11805674j,  0.08310692+0.37568066j,
          0.3351953 +0.57798448j],
        [-0.66630111-0.12570169j, -0.47009285-0.22499096j,
         -0.02697209-0.51759656j]])

In [11244904]:
abs(Out['494a6a'] - Z*T*Z.H)

matrix([[1.77635684e-15, 3.55271368e-15, 4.88498131e-15],
        [2.22044605e-15, 3.55271368e-15, 6.21724894e-15],
        [2.66453526e-15, 3.10862447e-15, 7.99360578e-15]])

In [15849476]:
abs(Out['494a6a'] - Z1*T1*Z1.H)

matrix([[6.66133815e-16, 4.89387476e-15, 2.70599070e-15],
        [1.96183037e-15, 1.15548565e-14, 1.59875970e-14],
        [2.35252041e-15, 1.15511223e-14, 1.77639153e-14]])

In [14514333]:
abs(Out['494a6a'] - Z2*T2*Z2.H)

matrix([[6.66133815e-16, 4.89387476e-15, 2.70599070e-15],
        [1.96183037e-15, 1.15548565e-14, 1.59875970e-14],
        [2.35252041e-15, 1.15511223e-14, 1.77639153e-14]])

## Arbitrary functions

In [3741093]:
from scipy import special, random
np.random.seed(1234)
random.rand(3,3)

<module 'numpy.random' from '/home/pc/miniconda3/lib/python3.6/site-packages/numpy/random/__init__.py'>

<module 'scipy.special' from '/home/pc/miniconda3/lib/python3.6/site-packages/scipy/special/__init__.py'>

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261],
       [0.27646426, 0.80187218, 0.95813935]])

In [415056]:
linalg.funm(Out['3915a5'], lambda x: special.jv(0,x))

array([[ 0.86511146, -0.19676526, -0.13856748],
       [-0.17479869,  0.7259118 , -0.16606258],
       [-0.19212044, -0.32052767,  0.73590704]])

In [7571005]:
linalg.eigvals(Out['3915a5'])

array([ 1.7388151 +0.j, -0.20270676+0.j,  0.39352627+0.j])

In [2528569]:
special.jv(0, linalg.eigvals(Out['3915a5']))

array([0.37551908+0.j, 0.98975384+0.j, 0.96165739+0.j])

In [2150066]:
linalg.eigvals(Out['065550'])

array([0.37551908+0.j, 0.98975384+0.j, 0.96165739+0.j])